kind: pipeline
name: code-server

steps:
  - name: build-server
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password: 
        from_secret: docker_password
      registry: registry.eu-central-1.aliyuncs.com
      repo: registry.eu-central-1.aliyuncs.com/axeler4t0r/code-server
      tags: ci